FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        ffmpeg \
        libgl1 \
        libglib2.0-0 \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps
COPY requirements-docker.txt /tmp/requirements-docker.txt
RUN pip install --no-cache-dir -r /tmp/requirements-docker.txt

# Let compose choose the service folder
ARG SERVICE_PATH=.
COPY ${SERVICE_PATH}/ /app/

#copy the model folder from build context root into container root
COPY MolmoE-1B-0924-NF4 /MolmoE-1B-0924-NF4
